### ISSUE TITLE
install脚本有问题

### ISSUE THREAD

**Issue by vianer** [hujingguang/OpsSystem#2]
安装好之后，yum,pip,setuptools,python都不能正常运行了；
节选一部分错误：
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/index.py", line 29, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler
Traceback (most recent call last):
  File "/usr/local/python2.7/bin/pip", line 9, in <module>
    load_entry_point('pip==8.0.2', 'console_scripts', 'pip')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2569, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2229, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2235, in resolve
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/**init**.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/index.py", line 29, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler
Traceback (most recent call last):
  File "/usr/local/python2.7/bin/pip", line 9, in <module>
    load_entry_point('pip==8.0.2', 'console_scripts', 'pip')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2569, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2229, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 2235, in resolve
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/**init**.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/index.py", line 29, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/usr/local/python2.7/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler
install pexpect salt django MySQL-pytho is ok ....................................
install git subversion ...............................
install salt-master failed

**Comment by hujingguang** [comment]
你的系统版本centos6.x吗 @vianer

**Comment by vianer** [comment]
Centos7

**Comment by hujingguang** [comment]
只支持centos6.x @vianer
